<?xml version="1.0" encoding="UTF-8"?>
<process name="cnn" categ="" pi_size_addr_rel="0" desc="">
  <parts>
    <part name="main">
      <svg width="127" height="127">
        <rect width="127" height="127" x="0" y="0" fill="lightgray"/>
        <text x="50" y="50">CNN</text>
      </svg>
    </part>
  </parts>
  <files>
	<file name="bitwidths.vhd"          type="vhdl" group="hdl"      path="../test/bitwidths.vhd"/>
    <file name="cnn_types.vhd"          type="vhdl" group="hdl"      path="../haddocLib/cnn_types.vhd"/>
    <file name="params.vhd"             type="vhdl" group="hdl"      path="../test/params.vhd"/>
    <file name="to_signedPixel.vhd"     type="vhdl" group="hdl"      path="../haddocLib/to_signedPixel.vhd"/>
    <file name="display_mux.vhd"        type="vhdl" group="hdl"      path="../haddocLib/display_mux.vhd"/>
    <file name="taps.vhd"               type="vhdl" group="hdl"      path="../haddocLib/taps.vhd"/>
    <file name="neighExtractor.vhd"     type="vhdl" group="hdl"      path="../haddocLib/neighExtractor.vhd"/>
    <file name="convElement.vhd"        type="vhdl" group="hdl"      path="../haddocLib/convElement.vhd"/>
    <file name="sumElement_single.vhd"  type="vhdl" group="hdl"      path="../haddocLib/sumElement_single.vhd"/>
    <file name="sumElement.vhd"         type="vhdl" group="hdl"      path="../haddocLib/sumElement.vhd"/>
    <file name="poolH.vhd"              type="vhdl" group="hdl"      path="../haddocLib/poolH.vhd"/>
    <file name="poolV.vhd"              type="vhdl" group="hdl"      path="../haddocLib/poolV.vhd"/>
    <file name="maxPool.vhd"            type="vhdl" group="hdl"      path="../haddocLib/maxPool.vhd"/>
    <file name="firstLayer.vhd"         type="vhdl" group="hdl"      path="../haddocLib/firstLayer.vhd"/>
    <file name="convLayer.vhd"          type="vhdl" group="hdl"      path="../haddocLib/convLayer.vhd"/>
    <file name="poolLayer.vhd"          type="vhdl" group="hdl"      path="../haddocLib/poolLayer.vhd"/>
    <file name="cnn_process.vhd"        type="vhdl" group="hdl"      path="../test/cnn_process.vhd"/>
    <file name="cnn_slave.vhd"          type="vhdl" group="hdl"      path="cnn_slave.vhd"/>
    <file name="cnn.vhd"                type="vhdl" group="hdl"      path="cnn.vhd"/>
    <file name="cnn.proc"               type="proc" group="blockdef" path="cnn.proc"/>
  </files>

  <resets>
    <reset name="reset_n" group="reset_n" direction="in"/>
  </resets>

  <flows>
    <flow name="in" size="8" type="in" desc="Input image to describe"/>

    <flow name="out" size="8" type="out" desc="conv1">
      <properties>
        <property name="datatype" type="flowtype" value="image"/>
        <property name="width"    type="int"  value="320"/>
        <property name="height"   type="int"  value="320"/>
      </properties>
  </flow>
  </flows>
  <params>
    <param name="IMAGE_WIDTH" type="int" hard="1" value="322" desc="maximum line width"/>
    <param name="control" regaddr="0" default="0" desc="Status Control Register">
      <bitfields>
        <bitfield name="enable" bitfield="0" propertymap="enable.value" desc="On/Off bit"/>
      </bitfields>
    </param>
    <param name="select_param" regaddr="1" propertymap="Selection.value" default="0" desc="Output to display"/>
  </params>

  <properties>
    <property name="enable"      type="bool" value="false"                 desc="Enable or disable process"/>
    <property name="Selection"   type="int"  value="0"     min="0" max="50" desc="Output to display"/>
  </properties>


</process>
